# Generated by Django 5.2.17 on 2026-08-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=160)),
                ('listing', models.CharField(blank=True, help_text="Exchange listing or note, e.g. 'BSE, NSE listed'.", max_length=80)),
                ('tier', models.CharField(choices=[('major', 'Major engagement'), ('other', 'Other client')], default='other', max_length=8)),
            ],
            options={
                'ordering': ['tier', 'order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirmValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('quality', 'Quality'), ('reliability', 'Reliability'), ('response', 'Responsiveness'), ('governance', 'Governance'), ('people', 'Our people'), ('partnership', 'Partnership')], default='quality', max_length=24)),
            ],
            options={
                'verbose_name': 'firm value',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'industry segment',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('direct-tax', 'Direct Tax'), ('indirect-tax', 'GST & Indirect Tax'), ('audit', 'Audit & Assurance'), ('regulatory', 'Regulatory'), ('advisory', 'Advisory'), ('firm', 'Firm News')], default='firm', max_length=20)),
                ('published_on', models.DateField(help_text='Date shown on the card.')),
                ('excerpt', models.CharField(help_text='One or two lines shown in listings.', max_length=300)),
                ('body', models.TextField(help_text='Full note. Separate paragraphs with a blank line.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='KeyFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('value', models.CharField(help_text="e.g. '20+', '2019', '9'", max_length=24)),
                ('label', models.CharField(help_text="e.g. 'Professionals across the practice'", max_length=80)),
            ],
            options={
                'verbose_name': 'key figure',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('city', models.CharField(max_length=80)),
                ('address', models.TextField(help_text='Street address. Line breaks are preserved.')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'city'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresenceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=80)),
                ('is_direct', models.BooleanField(default=True, help_text='Untick if covered through associates.')),
            ],
            options={
                'verbose_name': 'presence city',
                'verbose_name_plural': 'presence cities',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('summary', models.CharField(help_text='One line shown in listings.', max_length=300)),
                ('intro', models.TextField(blank=True, help_text='Opening paragraphs on the service page. Separate with a blank line.')),
                ('deliverables', models.TextField(blank=True, help_text='One deliverable per line.')),
                ('icon', models.CharField(choices=[('audit', 'Audit'), ('tax', 'Tax'), ('risk', 'Risk'), ('governance', 'Governance'), ('finance', 'Corporate finance'), ('outsourcing', 'Outsourcing'), ('analytics', 'Analytics'), ('digital', 'Digital')], default='audit', help_text='Line icon shown on the service card.', max_length=24)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page.')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('designation', models.CharField(help_text="e.g. 'Partner'", max_length=120)),
                ('focus', models.CharField(help_text='Practice areas.', max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(help_text='Two or three short paragraphs. Separate with a blank line.')),
                ('key_skills', models.TextField(blank=True, help_text='One skill per line.')),
                ('sectors', models.TextField(blank=True, help_text='One sector per line.')),
                ('qualification', models.CharField(blank=True, max_length=240)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('photo', models.ImageField(blank=True, help_text='Square image, at least 600x600.', upload_to='team/')),
                ('static_photo', models.CharField(blank=True, help_text="Bundled fallback image, e.g. 'site/img/team/anuj-kumar.jpg'.", max_length=200)),
                ('is_lead', models.BooleanField(default=False, help_text='Feature this person first.')),
            ],
            options={
                'ordering': ['-is_lead', 'order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=12)),
                ('internal_notes', models.TextField(blank=True, help_text='Not shown on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_page', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('service_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='profile_site.service', verbose_name='service of interest')),
            ],
            options={
                'verbose_name': 'contact enquiry',
                'verbose_name_plural': 'contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
